dependencies:
  - scipy
  - sympy
  - quantities
  - astroML
  - healpy
  - matplotlib
  - numpy
  - pandas
  - pip
  - pytest
  - ipywidgets >= 6.0.0
  - jupyterlab_latex
  - pip:
      - julia
      - nbval
      - nbdime
