name: hubble-radius
#channels:
#  - conda-forge
dependencies:
  - python =3.7
  - numpy
  - matplotlib
  - pandas
  - sympy
  - scipy
  #- quantities
  - pillow
  - ipywidgets
  - ipypublish-environment
  - jupyterlab              # ==0.35
  - jupyterlab_latex        # ==0.4.1
  - notebook                # ==5.7.4
