name: hubble-radius
#channels:
#  - conda-forge
dependencies:
  - python =3.7
  - numpy
  - matplotlib
  - pandas
  - sympy
  - scipy
  - quantities
  - astroML
  - healpy
  - pillow
  - ipywidgets
  - jupyterlab =0.35
  - notebook =5.7.4
  - pip
  - pytest


  # - ipypublish-environment
  # - jupyterlab_latex       ==0.4.1
