name: hubble-radius
channels:
  - conda-forge
dependencies:
  - python=3.8  # Updated Python version
  - numpy
  - matplotlib
  - pandas
  - sympy
  - scipy
  - quantities
  - astroML
  - healpy
  - pillow
  - ipywidgets
  - jupyterlab=3.0  # Updated JupyterLab version
  - notebook=6.4.0  # Updated Notebook version
  - pip
  - pytest
  - pip:
      - julia
      - nbval
      - nbdime
      - jupyterlab_latex
      - ipypublish
